CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cliente VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    telefone VARCHAR(32) NOT NULL,
    email VARCHAR(100) NOT NULL,
    dt_nascimento DATE
);

CREATE TABLE imoveis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_imovel VARCHAR(50) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    cep VARCHAR(20) NOT NULL,
    dormitorios INT,
    banheiros INT,
    suites INT,
    metragem INT,
    valor_aluguel_sug DECIMAL(12,2),
    obs TEXT
);

CREATE TABLE locacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_imovel BIGINT NOT NULL,
    id_inquilino BIGINT NOT NULL,
    ativo BOOLEAN,
    data_fim DATE,
    data_inicio DATE NOT NULL,
    dia_vencimento INT,
    percentual_taxa DECIMAL(7,2),
    valor_aluguel DECIMAL(12,2),
    obs TEXT,
    CONSTRAINT fk_locacao_imovel FOREIGN KEY (id_imovel) REFERENCES imoveis(id),
    CONSTRAINT fk_locacao_inquilino FOREIGN KEY (id_inquilino) REFERENCES clientes(id)
);
